Repository co-cddo/ukgov-metadata-exchange-model, pull requests merged in 2023-10, with the labels that each got.

#36 Consistent definition of slots within the model
  src/model/uk_cross_government_metadata_exchange_model.yaml
Labels: enhancement, infrastructure

#42 Dealing with dependabot updates
  README.md
Labels: documentation, infrastructure

#47 Fix #46 heading only displays if there is content
  src/docs/templates/slot.md.jinja2
Labels: bug, infrastructure

#48 Show full enum description
  src/docs/templates/enum.md.jinja2
Labels: bug, documentation, enhancement, infrastructure

#41 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#53 Guidance text for the version property
  src/model/uk_cross_government_metadata_exchange_model.yaml
Labels: documentation, enhancement

#55 Add overview text to documentation site
  src/docs/about.md
  src/docs/miwg.md
  src/docs/templates/index.md.jinja2
  src/model/uk_cross_government_metadata_exchange_model.yaml
Labels: documentation, enhancement

#58 Improved guidance for the mediaType property
  src/data/Distribution/invalid/invalid-mediatype-csv.yaml
  src/data/Distribution/invalid/invalid-mediatype-uri.yaml
  src/data/Distribution/invalid/multiple-mediatype.yaml
  src/data/Distribution/valid/Distribution-os-postcodes-excel-distribution-minimal.yaml
  src/model/uk_cross_government_metadata_exchange_model.yaml
Labels: documentation, enhancement, Model

#62 Fix Enum URI links
  src/docs/templates/enum.md.jinja2
Labels: bug, infrastructure
